name: "test"

on:
  push:
    paths:
      - "packages/**"
  pull_request:
    paths:
      - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [angular, dotnet, gleam, haskell, java, node, python, rust]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop .#${{ matrix.language }}
