name: "test"

on:
  pull_request:
  push:

jobs:
  dotnet:
    name: "Test: dotnet devenv"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop .#dotnet
      - run: which dotnet

  python:
    name: "Test: python devenv"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix develop .#python
      - run: which python pip pipx
