name: "test"

on:
  push:
    paths:
      - ".github/**"
      - "packages/**"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [angular, dotnet, gleam, haskell, java, node, python, rust]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop .#${{ matrix.language }}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        language: [dotnet, gleam, haskell, java, node, python, rust]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop .#${{ matrix.language }}
